import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const baileys = require('./index.js');

export const makeWASocket = baileys.default || baileys.makeWASocket;
export const DisconnectReason = baileys.DisconnectReason;
export const useMultiFileAuthState = baileys.useMultiFileAuthState;
export const fetchLatestBaileysVersion = baileys.fetchLatestBaileysVersion;
export const makeCacheableSignalKeyStore = baileys.makeCacheableSignalKeyStore;
export const makeInMemoryStore = baileys.makeInMemoryStore;
export const jidDecode = baileys.jidDecode;
export const proto = baileys.proto;
export const getContentType = baileys.getContentType;
export const generateWAMessageFromContent = baileys.generateWAMessageFromContent;
export const prepareWAMessageMedia = baileys.prepareWAMessageMedia;
export const areJidsSameUser = baileys.areJidsSameUser;
export const downloadContentFromMessage = baileys.downloadContentFromMessage;
export const generateMessageID = baileys.generateMessageID;
export const getDevice = baileys.getDevice;
export const WAProto = baileys.WAProto;
export const WAMessageStubType = baileys.WAMessageStubType;
export const extractMessageContent = baileys.extractMessageContent;
export const generateForwardMessageContent = baileys.generateForwardMessageContent;
export const Browsers = baileys.Browsers;
export const jidNormalizedUser = baileys.jidNormalizedUser;
export const getBinaryNodeChildren = baileys.getBinaryNodeChildren;
export const getBinaryNodeChild = baileys.getBinaryNodeChild;
export const generateWAMessageContent = baileys.generateWAMessageContent;
export const S_WHATSAPP_NET = baileys.S_WHATSAPP_NET;
export const delay = baileys.delay;
export const fetchLatestWaWebVersion = baileys.fetchLatestWaWebVersion;
export const getAggregateVotesInPollMessage = baileys.getAggregateVotesInPollMessage;
export default baileys;
